# All distances explanation can be found in a figure in this folder (Strirus_points_diagram.png)
distances: { dist_btw_legs: 0.106 }
leg: { mass: 0.051, thickness: 0.013, height: 0.08,
       CoM: { x: -0.013348671, y: 0, z: 0 },
       inertia: { ixx: 1.020E-04, ixy: 0, ixz: -2.817E-05, iyy: 1.322E-04, iyz: 0, izz: 3.167E-05 }
}

body_1: { mass: 0.665,
          CoM: { x: 0.101, y: 0, z: -0.002 },
          inertia: { ixx: 0.005, ixy: 0, ixz: 1.366E-04, iyy: 0.013, iyz: 0, izz: 0.017 },
          coords: { 0_deg_motor_box_close: { x: 0, y: 0.046, z: 0 },
                    0_deg_motor_box_far: { x: 0, y: 0.063, z: 0 },
                    15_deg_motor_box: { x: 0.016, y: 0.0701, z: 0 },
                    30_deg_motor_box: { x: 0.018, y: 0.0988, z: 0 },
                    45_deg_motor_box: { x: 0.0191, y: 0.1109, z: 0 },
                    bridge_1: { x: 0.247, y: 0, z: 0 },
                    imu_1: { x: 0, y: 0, z: 0 },
                    tof_camera_1: { x: -0.0245, y: 0, z: 0 },
          }
}

body_2: { mass: 0.665,
          CoM: { x: 0.146, y: 0, z: -0.002 },
          inertia: { ixx: 0.005, ixy: 1.656E-06, ixz: 2.448E-04, iyy: 0.02, iyz: -2.631E-08, izz: 0.024 },
          coords: { 0_deg_motor_box_close: { x: 0.035, y: 0.046, z: 0 },
                    0_deg_motor_box_far: { x: 0.035, y: 0.063, z: 0 },
                    15_deg_motor_box: { x: 0.019, y: 0.0701, z: 0 },
                    30_deg_motor_box: { x: 0.017, y: 0.0988, z: 0 },
                    45_deg_motor_box: { x: 0.0159, y: 0.1109, z: 0 },
                    imu_2: { x: 0.2226, y: 0, z: 0 },
                    tof_camera_2: { x: 0.2715, y: 0, z: 0 },
          }
}


bridge_1: { mass: 0.147,
            CoM: { x: 0.005, y: 0, z: 0 },
            inertia: { ixx: 3.384E-04, ixy: 0, ixz: 0, iyy: 5.442E-05, iyz: 0, izz: 3.303E-04 },
            coords: { bridge_2: { x: 0.03, y: 0, z: 0 }
            }
}

bridge_2: { mass: 0.147,
            CoM: { x: 0.025, y: 0, z: 0 },
            inertia: { ixx: 3.654E-04, ixy: 0, ixz: -1.872E-06, iyy: 1.394E-04, iyz: 0, izz: 4.423E-04 },
            coords: { body_2: { x: 0.03, y: 0, z: 0 }
            }
}

motor_box: { mass: 0.286,
             CoM: { x: 0.053, y: 0.003, z: 0 },
             inertia: { ixx: 8.104E-05, ixy: 8.747E-06, ixz: 2.555E-07, iyy: 0.001, iyz: 0, izz: 0.001 },
             coords: { leg: { x: 0.1165, y: 0, z: 0 }
             }
}