image: 
    name: registry.gitlab.com/inno20_eurobot_full/inno20_eurobot_control/pipeline:root_user
    entrypoint: [""]

variables:
  ROS_PYTHON_VERSION: 3

before_script:
    - rm -rf /root/catkin_ws/src/*
    # making a symlink to the project, for making the pipeline work correctly
    - ln -s /builds/inno20_eurobot_full/inno20_eurobot_control /root/catkin_ws/src
    - cd /root/catkin_ws/src
    - echo $(pwd)
    - echo $ROS_PYTHON_VERSION
    - tree -l .
    - echo $(pwd)
    - python3 -V

stages:
  - lint-cpp                        
  - lint-python                     
  - lint-xml                        
  - build                           
  - unit-and-integration-tests

linter_cpp:
  stage: lint-cpp
  script:
    - cpplint --filter=-whitespace,-legal/copyright,-readability/multiline_comment,-build/c++11,-runtime/references --recursive */*
  only:
    - master
    - merge_requests

linter_python:
  stage: lint-python
  script:
    - flake8 --ignore=D400,D415,W503 --per-file-ignore='**/test/**:D' --exclude='**/__init__.py **/setup.py' --docstring-convention=google /builds/inno20_eurobot_full/inno20_eurobot_control
  only:
    - master
    - merge_requests

linter_xml:
  stage: lint-xml
  script:
    - xmllint --noout $(find . -type f -name "*.launch" -exec echo {} \;)
  only:
    - master
    - merge_requests

catkin_build:
  stage: build
  script: 
    - catkin build
  only:
    - master
    - merge_requests

run_catkin_tests:
  stage: unit-and-integration-tests
  script: 
    - cd /root/catkin_ws
    - catkin build
    - source /root/catkin_ws/devel/setup.bash
    - catkin run_tests
    - source /root/catkin_ws/devel/setup.bash
    - catkin_test_results
  only:
    - master
    - merge_requests

show_coverage:
  stage: unit-and-integration-tests
  script:
    - cd /root/catkin_ws
    - catkin build
    - source /root/catkin_ws/devel/setup.bash
    - nosetests --with-coverage $(ls -d src/** | sed -e "s/src\///" | sed 's/^/--cover-package /' | tr '\n' ' ')
  only:
    - master
    - merge_requests
  allow_failure: true
 
