# These controlles also should be mentioned in roslaunch args
strirus_robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50 
    
  # Effort controllers

  # # Position Controllers Left Joint ---------------------------------------
  # joint5_position_controller_l:
  #   type: effort_controllers/JointPositionController
  #   joint: leg_left_5_revolute_joint
  #   pid: {p: 10.0, i: 1.0, d: 0.0}
  # joint4_position_controller_l:
  #   type: effort_controllers/JointPositionController
  #   joint: leg_left_4_revolute_joint
  #   pid: {p: 10.0, i: 1.0, d: 0.0}
  # joint3_position_controller_l:
  #   type: effort_controllers/JointPositionController
  #   joint: leg_left_3_revolute_joint
  #   pid: {p: 10.0, i: 1.0, d: 0.0}
  # joint2_position_controller_l:
  #   type: effort_controllers/JointPositionController
  #   joint: leg_left_2_revolute_joint
  #   pid: {p: 10.0, i: 1.0, d: 0.0}
  # joint1_position_controller_l:
  #   type: effort_controllers/JointPositionController
  #   joint: leg_left_1_revolute_joint
  #   pid: {p: 10.0, i: 1.0, d: 0.0}
  # joint0_position_controller_l:
  #   type: effort_controllers/JointPositionController
  #   joint: leg_left_0_revolute_joint
  #   pid: {p: 10.0, i: 1.0, d: 0.0}
  # # Position Controllers Right Joint ---------------------------------------
  # joint5_position_controller_r:
  #   type: effort_controllers/JointPositionController
  #   joint: leg_right_5_revolute_joint
  #   pid: {p: 10.0, i: 1.0, d: 0.0}
  # joint4_position_controller_r:
  #   type: effort_controllers/JointPositionController
  #   joint: leg_right_4_revolute_joint
  #   pid: {p: 10.0, i: 1.0, d: 0.0}
  # joint3_position_controller_r:
  #   type: effort_controllers/JointPositionController
  #   joint: leg_right_3_revolute_joint
  #   pid: {p: 10.0, i: 1.0, d: 0.0}
  # joint2_position_controller_r:
  #   type: effort_controllers/JointPositionController
  #   joint: leg_right_2_revolute_joint
  #   pid: {p: 10.0, i: 1.0, d: 0.0}
  # joint1_position_controller_r:
  #   type: effort_controllers/JointPositionController
  #   joint: leg_right_1_revolute_joint
  #   pid: {p: 10.0, i: 1.0, d: 0.0}
  # joint0_position_controller_r:
  #   type: effort_controllers/JointPositionController
  #   joint: leg_right_0_revolute_joint
  #   pid: {p: 10.0, i: 1.0, d: 0.0}

# Position controllers

  # Position Controllers Left Joint ---------------------------------------
  joint5_position_controller_l:
    type: position_controllers/JointPositionController
    joint: leg_left_5_revolute_joint
  joint4_position_controller_l:
    type: position_controllers/JointPositionController
    joint: leg_left_4_revolute_joint
  joint3_position_controller_l:
    type: position_controllers/JointPositionController
    joint: leg_left_3_revolute_joint
  joint2_position_controller_l:
    type: position_controllers/JointPositionController
    joint: leg_left_2_revolute_joint
  joint1_position_controller_l:
    type: position_controllers/JointPositionController
    joint: leg_left_1_revolute_joint
  joint0_position_controller_l:
    type: position_controllers/JointPositionController
    joint: leg_left_0_revolute_joint
  # Position Controllers Right Joint ---------------------------------------
  joint5_position_controller_r:
    type: position_controllers/JointPositionController
    joint: leg_right_5_revolute_joint
  joint4_position_controller_r:
    type: position_controllers/JointPositionController
    joint: leg_right_4_revolute_joint
  joint3_position_controller_r:
    type: position_controllers/JointPositionController
    joint: leg_right_3_revolute_joint
  joint2_position_controller_r:
    type: position_controllers/JointPositionController
    joint: leg_right_2_revolute_joint
  joint1_position_controller_r:
    type: position_controllers/JointPositionController
    joint: leg_right_1_revolute_joint
  joint0_position_controller_r:
    type: position_controllers/JointPositionController
    joint: leg_right_0_revolute_joint