joint_limits:
    joint5_position_controller_r:
      has_position_limits: true
      min_position: -1.57
      max_position: -1.57
      has_velocity_limits: false
      max_velocity: 1.0472
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 255
      min_effort: -255
    joint4_position_controller_r:
      has_position_limits: true
      min_position: -1.57
      max_position: -1.57
      has_velocity_limits: false
      max_velocity: 1.0472
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 255
      min_effort: -255
    joint3_position_controller_r:
      has_position_limits: true
      min_position: -1.57
      max_position: -1.57
      has_velocity_limits: false
      max_velocity: 1.0472
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 255
      min_effort: -255
    joint2_position_controller_r:
      has_position_limits: true
      min_position: -1.57
      max_position: -1.57
      has_velocity_limits: false
      max_velocity: 1.0472
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 255
      min_effort: -255
    joint1_position_controller_r:
      has_position_limits: true
      min_position: -1.57
      max_position: -1.57
      has_velocity_limits: false
      max_velocity: 1.0472
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 255
      min_effort: -255
    joint0_position_controller_r:
      has_position_limits: true
      min_position: -1.57
      max_position: -1.57
      has_velocity_limits: false
      max_velocity: 1.0472
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 255
      min_effort: -255

    joint5_position_controller_l:
      has_position_limits: true
      min_position: -1.57
      max_position: -1.57
      has_velocity_limits: false
      max_velocity: 1.0472
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 255
      min_effort: -255
    joint4_position_controller_l:
      has_position_limits: true
      min_position: -1.57
      max_position: -1.57
      has_velocity_limits: false
      max_velocity: 1.0472
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 255
      min_effort: -255
    joint3_position_controller_l:
      has_position_limits: true
      min_position: -1.57
      max_position: -1.57
      has_velocity_limits: false
      max_velocity: 1.0472
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 255
      min_effort: -255
    joint2_position_controller_l:
      has_position_limits: true
      min_position: -1.57
      max_position: -1.57
      has_velocity_limits: false
      max_velocity: 1.0472
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 255
      min_effort: -255
    joint1_position_controller_l:
      has_position_limits: true
      min_position: -1.57
      max_position: -1.57
      has_velocity_limits: false
      max_velocity: 1.0472
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 255
      min_effort: -255
    joint0_position_controller_l:
      has_position_limits: true
      min_position: -1.57
      max_position: -1.57
      has_velocity_limits: false
      max_velocity: 1.0472
      has_acceleration_limits: false
      max_acceleration: 0.0
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 255
      min_effort: -255